baseURL = "https://www.shenquanquan.com/"
languageCode = "zh-cn"
title = "神券券"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = true
buildExpired = false

# Google Analytics 4 配置
[services.googleAnalytics]
  ID = "G-H4VLTG8CRF"

# PaperMod 主题配置
[params]
  env = "production"
  title = "神券券"
  description = "神券券 - 最新优惠信息，省钱必备"
  keywords = ["优惠券", "折扣", "省钱", "购物", "外卖", "美团", "饿了么", "京东", "淘宝闪购"]
  author = "神券券"
  
  # 显示相关配置
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
  
  # 禁用主题切换和搜索按钮
  disableThemeToggle = true
  disableSearchToggle = true

  # 网站图标配置
  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"

  # 使用自定义首页模板显示最新文章
  
  # 自定义副标题
  subtitle = "神券券 - 为您提供最新、最全的优惠信息"

  # 社交链接
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/oomaidou"

# 主导航菜单配置
[[menu.main]]
  identifier = "home"
  name = "优惠头条"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "coupons"
  name = "优惠券大全"
  url = "/coupons/"
  weight = 20

# 允许在Markdown中使用HTML
[markup.goldmark.renderer]
  unsafe = true

# 多语言支持
[languages.zh-cn]
  languageName = "简体中文"
  weight = 1